[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
transition = 0.7
storymode = false
storymodemethod = 1
storymode_max_length = 1000
fps = 30
resolution_w = 1080
resolution_h = 1920

[settings.background]
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"
background_choice = "minecraft"

[settings.tts]
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = ""
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.5
no_emojis = false
voice_choice = "streamlabspolly"

[reddit.creds]
client_id = "mGFxLvYejv3s3hRipxUo2Q"
client_secret = "AmXSmyRJsNOd98n5CyvY8hMv76D_7g"
username = "Asp_-00x38-0x0-"
password = "===MustafaBaban2321976"
2fa = false

[reddit.thread]
random = true
subreddit = "AskReddit"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20
